### ISSUE TITLE
XC area formula assumes proper zero coordinate

### ISSUE THREAD

**Issue by speleophysics** [mcooper12590/CaveXC#3]
The formula used to calculate XC area CrossSection.calcA() breaks down under certain conditions. It works for any closed shape if the zero coordinate of the XC is within the shape. However, it only works for vadose wet cross-sections if the zero of the cross-section coordinate system is located at the water surface (i.e. y=0 is the water surface). I couldn't tell whether the vadose simulation code somehow corrects for this by resetting the zero. In any case, it would be more robust to do this check, or correction, within the calcA function. The formula can be corrected by subtracting out the y coord of the water surface (or max y coord in the case of only a wet cross-section).

**Comment by mcooper12590** [comment]
This is due to using a range for xm, ym when calculating area with the formula within calcA instead of using roll(). The points (x[l:r], y[l:r]), (xm[l:r], ym[l:r]) do not make the same polygon as required for the formula as the subset (xm[l:r], ym[l:r]) do not 'wrap' around. If using a subset use

A = fabs( 0.5 * (x[l:r]*(roll(y[l:r],1)) - (roll(x[l:r],1)*(y[l:r]).sum() )

instead. Note that when creating a separate wetted cross-section (CrossSection(x[l:r], y[l:r]) the calculation in calcA holds as xm, ym are rolled on creation of the object.
